# Generated by Django 4.1 on 2022-08-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
